# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: pygments
plugins: [jekyll-paginate-v2]

pagination:
  enabled: true
  per_page: 3
  permalink: "/page/:num/"

comments: true

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: Hemershon
description: "Blog do Hemershon Silva, engenheiro de software Sênior a 7 anos desenvolvendo soluções web."
keywords: "ruby on rails, Postgresql, blog, web"
url: ""
baseurl: ""

google_analytics: UA-111493883-1
repo: https://github.com/hemershon/hemershon.github.io
disqus_shortname: "Hemershon"
disqus_site_shortname: "Hemershon"

# Author settings
author:
  name: Hemershon Silva
  job: Software Engineer
  bio: "Sou engenheiro de software que a 7 anos desenvolvo sistema para web"
  thumb: /images/author.png
  email: hemershon@gmail.com
  url: ""
  github: https://github.com/hemershon
  twitter: https://twitter.com/ohemershon
  facebook: https://facebook.com/
  linkedin: https://linkedin.com/in/hemershon-silva

# navbar pages
navbar:
  - slug: about
    title: Sobre
  # - slug: icons
  #   title: Icons
  - slug: blog
    title: Blog

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]
